### ISSUE TITLE
How does lla compare to `eza`?

### ISSUE THREAD

**Issue by aSapien** [triyanox/lla#41]
How does lla stack up against another well established rust-based alternative to `ls` named [eza](https://github.com/eza-community/eza)?

Both aim to replace `ls` on local dev machines, so why might one pick `lla` over `eza` or vice versa?

**Comment by brianmay** [comment]
I think the plugins is completely new concept to lla.

**Comment by triyanox** [comment]
Hey there @aSapien @brianmay! To answer this question, I have to tell you about the inspiration behind lla. You may have heard of [Raycast](https://www.raycast.com/), which is like Spotlight but for macOS. The idea of Raycast was to have a shortcut for everything, and this idea is brilliant because macOS users were using Spotlight search for one main purpose - to search for files. Raycast came up with a new way to create a centralized hub to take actions on many tools to enhance user productivity.
As everyone knows, ls is for listing files, but to do anything else, you have to use another tool. Nothing wrong with that, but with time you'll find yourself juggling between many tools and piecing together information from all those tools to come up with a conclusion. So the idea for lla, just like Raycast, starts with file listing but the vision is much broader - to have a way of integrating all sorts of tools into it and extend it to do anything. With the help of a community, we can build an ecosystem of plugins that add value to your everyday use.
For now, the plugin system is still under development as we work to create a better and more stable version. We're also focused on providing robust APIs for plugin developers to build and extend lla's functionality. Sometimes you want to build something that makes sense only for your use case and a small minority of users, and you can't push it to the main tool. That's where lla comes in - it gives you the tools to build solutions yourself and share them with the community. We're building not just a tool, but a platform where developers can create and share their own solutions for file management and analysis.
This approach sets lla apart from other ls alternatives like eza. While both tools aim to improve upon ls, lla's focus on extensibility and community-driven development creates possibilities for users to tailor the tool to their specific needs through plugins and customizations. The goal is to eliminate the need to switch between multiple tools by bringing all the functionality you need into one unified interface.

**Comment by aSapien** [comment]
Thanks for the detailed explanation @triyanox!
