### ISSUE TITLE
Git-aware view doesn't work with paths

### ISSUE THREAD

**Issue by RobertClarke64** [triyanox/lla#45]
I'm using the git-aware view, which works if you cd into a directory first and then run it, but you don't seem to be able to specify paths.

![image](https://github.com/user-attachments/assets/a7f8d0ad-e4f2-4d25-a146-7acc20372b0f)

Ideally I think you'd be able to specify a path as well.

**Comment by triyanox** [comment]
Hey @RobertClarke64 thank you for opening this issue, I've just released v0.3.0 which fix a lot of issues we've had before including ABI stability for the plugin system and other minor bugs like this one, as you can see I'm using the v0.3.0 and it's working without any issues

<img width="1018" alt="Screenshot 2024-12-11 at 12 15 52" src="https://github.com/user-attachments/assets/68e1c8f4-5b7d-44dc-a01c-a64d800c5b23">


so in order to use the latest version if you've installed `lla` via cargo you can simply run

```bash
cargo install lla
lla clean # to clean previous incompatible plugins
# optionally you can install the latest versions of the plugins
```
