### ISSUE TITLE
documentation suggestion: --sizemap

### ISSUE THREAD

**Issue by seefood** [triyanox/lla#61]
When I first saw the screenshot I was thrilled, but the first I actually ran it locally I realised it's not recursive.
I usually use `du -sm * .??* | sort -n` and I was expecting this to be a graphic version of that. I suggest the README sould say clearly that it's not recursive (for now? until a plugin adds that?).

**Comment by triyanox** [comment]
Thank you @seefood for the suggestion, for now it's says clearly in the documentation `Visual representation of file sizes` not directories because the only listing format which uses a recursive lister is the `tree` format due to it being expected, for `sizemap` support only the current dir files, we can add some flag to make it account for directories too in a future release the idea of `du -sm * .??* | sort -n` is quite good actually!

**Comment by triyanox** [comment]
Hey @seefood, just shipped `v0.3.6` and you can use the `--include-dirs` flag to have the dirs size include in metadata as you can see in the screenshot, the flag works with all listing formats, also you can set it once in the config if that suits you best

![sizemap](https://github.com/user-attachments/assets/16dc37ac-7039-4921-9945-6a1dc4deaa43)

**Comment by seefood** [comment]
yup, it works, but then I remembered `ncdu` and it finished the scan in a fraction of the time, sorry :)

**Comment by triyanox** [comment]
@seefood Do you mean that it's slow because I already benchmarked it against `ncdu` because it's what I was using before and `lla` is faster, did you have a different experience? Let me know what you're experience was if that's the case!

**Comment by seefood** [comment]
first Linux machine I tried `lla --sizemap --include-dirs /` never returns (tried Debian 12, rocky 8) as it gets stuck in an endless loop in /dev or /sys

maybe it means kernel filesystems need a different treatment, or probably better to ignore them.

so I started with a mac laptop:
```
❯ time du -sh /*
2.56s user 52.08s system 29% cpu 3:03.10 total

❯ time ncdu / -o tmp1
2.60s user 80.37s system 39% cpu 3:31.38 total

❯ time lla --sizemap --include-dirs /
5.47s user 112.51s system 158% cpu 1:14.56 total
```
seems decent.

second try on linux, now skipping the same directories for all three time tests
```
# time for i in $(ls / | grep -v sys| grep -v dev) ;do echo $i ; lla --sizemap --include-dirs /$i ; done
real	0m53.570s
user	0m4.700s
sys	3m50.314s

# time for i in $(ls / | grep -v sys| grep -v dev) ;do echo $i ; du -sh /$i/* ; done
real	0m6.885s
user	0m1.177s
sys	0m5.574s

# time for i in $(ls / | grep -v sys| grep -v dev) ;do echo $i ; ncdu -o tmp1 /$i ; done
real	0m10.572s
user	0m1.744s
sys	0m8.536s
```

this isn't an exact measure, I would run on more systems to be sure and get more samples, but that's just a ballpark to be aware of. I don't know what was the first run I did when I got the first impression, I'll run a few more to be sure.

**Comment by triyanox** [comment]
Thank you so much @seefood for the detailed benchmarks, thanks to you I was able to find an issue because I was sharing the dir walking logic, I was following sym links when building the size map, and that can cause issues in very large dirs with sym links for example, it took some time to populate the size in node_modules using pnpm due to it using sym links to centralize the packages 

I tested in various dirs here is some of my findings, I will try to further fix some redundancies, overall now it's better now it takes a fraction of the time it took before, I will make some more enhancements and create a new release for it

<img width="1728" alt="Screenshot 2024-12-20 at 10 57 41" src="https://github.com/user-attachments/assets/469d4b27-1db8-4b28-ad96-5d939bf16042" />
<img width="1718" alt="Screenshot 2024-12-20 at 10 51 08" src="https://github.com/user-attachments/assets/5b7691fa-cdba-47f9-8128-a835f9d9caab" />

so thanks again @seefood
