### ISSUE TITLE
Consider using Cargo workspaces

### ISSUE THREAD

**Issue by pluiedev** [triyanox/lla#9]
`lla` has a lot of subcrates that can be neatly compiled together with [Cargo workspaces](https://doc.rust-lang.org/cargo/reference/workspaces.html) instead of the custom build script it has right now. This fits the paradigm of external build tools (e.g. Nix) much better and should overall be less of a hassle

**Comment by triyanox** [comment]
Thanks @pluiedev for this great suggestion! You're absolutely right about Cargo workspaces.
The reason I initially avoided workspaces was that plugins are built on install rather than being part of the main build. However, moving to workspaces would give better modularity and make it easier to manage the growing codebase. It'll make it cleaner to add new features and help contributors navigate the project structure.
I'll start working on migrating to a workspace setup. This should simplify the build process for both development and packaging.

**Comment by triyanox** [comment]
The migration to cargo workspaces is done successfully and it's being used for versions starting `v0.2.9`, thanks for the awesome suggestion.
